wikimedia_pageviews:
  target: prod
  outputs:
    prod:
      type: bigquery
      project: "wikimedia-pageviews"
      method: service-account
      keyfile: "../terraform/keys/my-credentials.json"
      dataset: "{{ vars.bigquery_dataset }}"
      threads: 4
      timeout_seconds: 300
      location: US