version: 2

models:
  - name: pageviews_partitioned
    description: "Creates a partitioned pageviews table"
    columns:
      - name: id
        description: "The primary key for this table"
      - name: language
        description: "Language of the wikipedia article"
      - name: project
        description: "Wikimedia project"
      - name: page_title
        description: "Title of the article"
      - name: views
        description: "Number of views or visits"
      - name: bytes
        description: "Data transferred"
      - name: date
        description: "Log date"
      - name: url
        description: "Data origin"

  - name: pageviews_summarized
    description: "Creates a summarized view of the pageviews table"
    columns:
      - name: id
        description: "The primary key for this table"
      - name: language
        description: "Language of the wikipedia article"
      - name: page_title
        description: "Title of the article"
      - name: views
        description: "Number of views or visits"
      - name: bytes
        description: "Data transferred"

  - name: top_by_language
    description: "Creates a summarized view of the pageviews table"
    columns:
      - name: id
        description: "The primary key for this table"
      - name: language
        description: "Language of the wikipedia article"
      - name: page_title
        description: "Title of the article"
      - name: views
        description: "Number of views or visits"
      - name: bytes
        description: "Data transferred"
